spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://49.235.169.216:3306/mmall?useunicode=true&characterEncoding=utf8
   username: root
   password: qq18924260161

mybatis:
 type-aliases-package: com.lc.mmallbook.pojo
 mapper-locations: classpath:mappers/*Mapper.xml